package view;

import java.awt.BorderLayout;
import java.awt.GridBagLayout;
import java.awt.GridLayout;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;

import javax.imageio.ImageIO;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;

import org.omg.CORBA.BAD_CONTEXT;

public class ImageLibrary extends JPanel{
	
	public Map<String, BufferedImage> imageDictionary = new HashMap<String, BufferedImage>();
	//BoxLayout by = new BoxLayout(this, BoxLayout.Y_AXIS);
	GridLayout gy = new GridLayout(2, 2);
	
	public ImageLibrary() {
		setLayout(gy);
		BufferedImage ghost = null;
		BufferedImage zero = null;
		BufferedImage luffy = null;
		BufferedImage lizardon = null;
		BufferedImage nanoha = null;
		BufferedImage cat = null;
		BufferedImage jojo = null;
		BufferedImage burger = null;
		BufferedImage happyface = null;
		BufferedImage clown = null;
		BufferedImage elmo = null;
		BufferedImage cookiemonster = null;
		BufferedImage abelardo = null;
		BufferedImage xd = null;
		BufferedImage clavin = null;
		BufferedImage sun = null;
		BufferedImage mohammed = null;
		BufferedImage hp = null;
		BufferedImage thething = null;
		BufferedImage kids = null;
		BufferedImage swim = null;
		BufferedImage blackkentuckychickenguy = null;
		BufferedImage blondgirl = null;
		BufferedImage interracial = null;
		BufferedImage gyaradous = null;
		BufferedImage masterchief = null;
		BufferedImage happyfire = null;
		BufferedImage littleblondgirl = null;
		BufferedImage togepi = null;
		BufferedImage moyashimon = null;
		BufferedImage carlostomate = null;
		BufferedImage nokidsallowed = null;
		BufferedImage dragon = null;
		BufferedImage eyelessgirl = null;
		BufferedImage halfbearhalfbear = null;
		BufferedImage mii = null;
		BufferedImage surffer = null;
		BufferedImage revolution = null;
		BufferedImage moon = null;
		BufferedImage heureusegateau = null;
		BufferedImage doratheexplorer = null;
		
		try {
			 ghost = ImageIO.read(ImageLibrary.class.getResourceAsStream("/images/1.jpg"));;
			 zero = ImageIO.read(ImageLibrary.class.getResourceAsStream("/images/2.jpg"));;
			 luffy = ImageIO.read(ImageLibrary.class.getResourceAsStream("/images/3.jpg"));;
			 lizardon = ImageIO.read(ImageLibrary.class.getResourceAsStream("/images/4.jpg"));;
			 nanoha = ImageIO.read(ImageLibrary.class.getResourceAsStream("/images/5.jpg"));;
			 cat = ImageIO.read(ImageLibrary.class.getResourceAsStream("/images/6.jpg"));;
			 jojo = ImageIO.read(ImageLibrary.class.getResourceAsStream("/images/7.jpg"));;
			 burger = ImageIO.read(ImageLibrary.class.getResourceAsStream("/images/8.jpg"));;
			 happyface = ImageIO.read(ImageLibrary.class.getResourceAsStream("/images/9.jpg"));;
			 clown = ImageIO.read(ImageLibrary.class.getResourceAsStream("/images/10.jpg"));;
			 elmo = ImageIO.read(ImageLibrary.class.getResourceAsStream("/images/11.jpg"));;
			 cookiemonster = ImageIO.read(ImageLibrary.class.getResourceAsStream("/images/12.jpg"));;
			 abelardo = ImageIO.read(ImageLibrary.class.getResourceAsStream("/images/13.jpg"));;
			 xd = ImageIO.read(ImageLibrary.class.getResourceAsStream("/images/14.jpg"));;
			 clavin = ImageIO.read(ImageLibrary.class.getResourceAsStream("/images/15.jpg"));;
			 sun = ImageIO.read(ImageLibrary.class.getResourceAsStream("/images/16.jpg"));;
			 mohammed = ImageIO.read(ImageLibrary.class.getResourceAsStream("/images/17.jpg"));;
			 hp = ImageIO.read(ImageLibrary.class.getResourceAsStream("/images/18.jpg"));;
			 thething = ImageIO.read(ImageLibrary.class.getResourceAsStream("/images/19.jpg"));;
			 kids = ImageIO.read(ImageLibrary.class.getResourceAsStream("/images/20.jpg"));;
			 swim = ImageIO.read(ImageLibrary.class.getResourceAsStream("/images/21.jpg"));;
			 blackkentuckychickenguy = ImageIO.read(ImageLibrary.class.getResourceAsStream("/images/22.jpg"));;
			 blondgirl = ImageIO.read(ImageLibrary.class.getResourceAsStream("/images/23.jpg"));;
			 interracial = ImageIO.read(ImageLibrary.class.getResourceAsStream("/images/24.jpg"));;
			 gyaradous = ImageIO.read(ImageLibrary.class.getResourceAsStream("/images/25.jpg"));;
			 masterchief = ImageIO.read(ImageLibrary.class.getResourceAsStream("/images/26.jpg"));;
			 happyfire = ImageIO.read(ImageLibrary.class.getResourceAsStream("/images/27.jpg"));;
			 littleblondgirl = ImageIO.read(ImageLibrary.class.getResourceAsStream("/images/28.jpg"));;
			 togepi = ImageIO.read(ImageLibrary.class.getResourceAsStream("/images/29.jpg"));;
			 moyashimon = ImageIO.read(ImageLibrary.class.getResourceAsStream("/images/30.jpg"));;
			 carlostomate = ImageIO.read(ImageLibrary.class.getResourceAsStream("/images/31.jpg"));;
			 nokidsallowed = ImageIO.read(ImageLibrary.class.getResourceAsStream("/images/32.jpg"));;
			 dragon = ImageIO.read(ImageLibrary.class.getResourceAsStream("/images/33.jpg"));;
			 eyelessgirl = ImageIO.read(ImageLibrary.class.getResourceAsStream("/images/34.jpg"));;
			 halfbearhalfbear = ImageIO.read(ImageLibrary.class.getResourceAsStream("/images/35.jpg"));;
			 mii = ImageIO.read(ImageLibrary.class.getResourceAsStream("/images/36.jpg"));;
			 surffer = ImageIO.read(ImageLibrary.class.getResourceAsStream("/images/37.jpg"));;
			 revolution = ImageIO.read(ImageLibrary.class.getResourceAsStream("/images/38.jpg"));;
			 moon = ImageIO.read(ImageLibrary.class.getResourceAsStream("/images/39.jpg"));;
			 heureusegateau = ImageIO.read(ImageLibrary.class.getResourceAsStream("/images/40.jpg"));;
			 doratheexplorer = ImageIO.read(ImageLibrary.class.getResourceAsStream("/images/41.jpg"));;
			
		} catch (IOException e) {	}
		
		imageDictionary.put("fantasma",  ghost );
		imageDictionary.put("enmascarado",  zero );
		imageDictionary.put("cultivador",  luffy );
		imageDictionary.put("lagarto",  lizardon );
		imageDictionary.put("nena1",  nanoha );
		imageDictionary.put("gato",  cat );
		imageDictionary.put("chico1",  jojo );
		imageDictionary.put("hamburguesa",  burger );
		imageDictionary.put("feliz",  happyface );
		imageDictionary.put("payaso",  clown );
		imageDictionary.put("elmo",  elmo );
		imageDictionary.put("monstruogalletas",  cookiemonster );
		imageDictionary.put("abelardo",  abelardo );
		imageDictionary.put("xD",  xd );
		imageDictionary.put("calvin",  clavin );
		imageDictionary.put("sol",  sun );
		imageDictionary.put("ejecutivo",  mohammed );
		imageDictionary.put("hp",  hp );
		imageDictionary.put("monstruo",  thething );
		imageDictionary.put("nenes",  kids );
		imageDictionary.put("nadador",  swim );
		imageDictionary.put("chico2",  blackkentuckychickenguy );
		imageDictionary.put("chica1",  blondgirl );
		imageDictionary.put("ajedrez",  interracial );
		imageDictionary.put("dragonasiatico",  gyaradous );
		imageDictionary.put("halo",  masterchief );
		imageDictionary.put("fueguito",  happyfire );
		imageDictionary.put("nena2",  littleblondgirl );
		imageDictionary.put("huevo",  togepi );
		imageDictionary.put("germen",  moyashimon );
		imageDictionary.put("carlostomate",  carlostomate );
		imageDictionary.put("prohibido",  nokidsallowed );
		imageDictionary.put("dragon",  dragon );
		imageDictionary.put("chica2",  eyelessgirl );
		imageDictionary.put("oso",  halfbearhalfbear );
		imageDictionary.put("mii",  mii );
		imageDictionary.put("surfista",  surffer );
		imageDictionary.put("letrero",  revolution );
		imageDictionary.put("luna",  moon );
		imageDictionary.put("pastelfeliz",  heureusegateau );
		imageDictionary.put("peruana",  doratheexplorer );
		
		JLabel lghost  = new JLabel(new ImageIcon(ghost));;
		JLabel lzero  = new JLabel(new ImageIcon(zero));;
		JLabel lluffy  = new JLabel(new ImageIcon(luffy));;
		JLabel llizardon  = new JLabel(new ImageIcon(lizardon));;
		JLabel lnanoha  = new JLabel(new ImageIcon(nanoha));;
		JLabel lcat  = new JLabel(new ImageIcon(cat));;
		JLabel ljojo  = new JLabel(new ImageIcon(jojo));;
		JLabel lburger  = new JLabel(new ImageIcon(burger));;
		JLabel lhappyface  = new JLabel(new ImageIcon(happyface));;
		JLabel lclown  = new JLabel(new ImageIcon(clown));;
		JLabel lelmo  = new JLabel(new ImageIcon(elmo));;
		JLabel lcookiemonster  = new JLabel(new ImageIcon(cookiemonster));;
		JLabel labelardo  = new JLabel(new ImageIcon(abelardo));;
		JLabel lxd  = new JLabel(new ImageIcon(xd));;
		JLabel lclavin  = new JLabel(new ImageIcon(clavin));;
		JLabel lsun  = new JLabel(new ImageIcon(sun));;
		JLabel lmohammed  = new JLabel(new ImageIcon(mohammed));;
		JLabel lhp  = new JLabel(new ImageIcon(hp));;
		JLabel lthething  = new JLabel(new ImageIcon(thething));;
		JLabel lkids  = new JLabel(new ImageIcon(kids));;
		JLabel lswim  = new JLabel(new ImageIcon(swim));;
		JLabel lblackkentuckychickenguy  = new JLabel(new ImageIcon(blackkentuckychickenguy));;
		JLabel lblondgirl  = new JLabel(new ImageIcon(blondgirl));;
		JLabel linterracial  = new JLabel(new ImageIcon(interracial));;
		JLabel lgyaradous  = new JLabel(new ImageIcon(gyaradous));;
		JLabel lmasterchief  = new JLabel(new ImageIcon(masterchief));;
		JLabel lhappyfire  = new JLabel(new ImageIcon(happyfire));;
		JLabel llittleblondgirl  = new JLabel(new ImageIcon(littleblondgirl));;
		JLabel ltogepi  = new JLabel(new ImageIcon(togepi));;
		JLabel lmoyashimon  = new JLabel(new ImageIcon(moyashimon));;
		JLabel lcarlostomate  = new JLabel(new ImageIcon(carlostomate));;
		JLabel lnokidsallowed  = new JLabel(new ImageIcon(nokidsallowed));;
		JLabel ldragon  = new JLabel(new ImageIcon(dragon));;
		JLabel leyelessgirl  = new JLabel(new ImageIcon(eyelessgirl));;
		JLabel lhalfbearhalfbear  = new JLabel(new ImageIcon(halfbearhalfbear));;
		JLabel lmii  = new JLabel(new ImageIcon(mii));;
		JLabel lsurffer  = new JLabel(new ImageIcon(surffer));;
		JLabel lrevolution  = new JLabel(new ImageIcon(revolution));;
		JLabel lmoon  = new JLabel(new ImageIcon(moon));;
		JLabel lheureusegateau  = new JLabel(new ImageIcon(heureusegateau));;
		JLabel ldoratheexplorer  = new JLabel(new ImageIcon(doratheexplorer));;	
		
		add( lghost );
		add( lzero );
		add( lluffy );
		add( llizardon );
		add( lnanoha );
		add( lcat );
		add( ljojo );
		add( lburger );
		add( lhappyface );
		add( lclown );
		add( lelmo );
		add( lcookiemonster );
		add( labelardo );
		add( lxd );
		add( lclavin );
		add( lsun );
		add( lmohammed );
		add( lhp );
		add( lthething );
		add( lkids );
		add( lswim );
		add( lblackkentuckychickenguy );
		add( lblondgirl );
		add( linterracial );
		add( lgyaradous );
		add( lmasterchief );
		add( lhappyfire );
		add( llittleblondgirl );
		add( ltogepi );
		add( lmoyashimon );
		add( lcarlostomate );
		add( lnokidsallowed );
		add( ldragon );
		add( leyelessgirl );
		add( lhalfbearhalfbear );
		add( lmii );
		add( lsurffer );
		add( lrevolution );
		add( lmoon );
		add( lheureusegateau );
		add( ldoratheexplorer );
	}
	
}
