package view;

import java.awt.BorderLayout;
import java.awt.GridBagLayout;
import java.awt.GridLayout;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;

import javax.imageio.ImageIO;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;

import org.omg.CORBA.BAD_CONTEXT;

public class ImageLibrary extends JPanel{
	
	public Map<String, BufferedImage> imageDictionary = new HashMap<String, BufferedImage>();
	GridLayout gy = new GridLayout(4, 2);
	
	public ImageLibrary(Editor e) {
		setLayout(gy);
		BufferedImage ghost = null;
		BufferedImage zero = null;
		BufferedImage luffy = null;
		BufferedImage lizardon = null;
		BufferedImage nanoha = null;
		BufferedImage cat = null;
		BufferedImage jojo = null;
		BufferedImage burger = null;
		BufferedImage happyface = null;
		BufferedImage clown = null;
		BufferedImage elmo = null;
		BufferedImage cookiemonster = null;
		BufferedImage abelardo = null;
		BufferedImage xd = null;
		BufferedImage clavin = null;
		BufferedImage sun = null;
		BufferedImage mohammed = null;
		BufferedImage hp = null;
		BufferedImage thething = null;
		BufferedImage kids = null;
		BufferedImage swim = null;
		BufferedImage blackkentuckychickenguy = null;
		BufferedImage blondgirl = null;
		BufferedImage interracial = null;
		BufferedImage gyaradous = null;
		BufferedImage masterchief = null;
		BufferedImage happyfire = null;
		BufferedImage littleblondgirl = null;
		BufferedImage togepi = null;
		BufferedImage moyashimon = null;
		BufferedImage carlostomate = null;
		BufferedImage nokidsallowed = null;
		BufferedImage dragon = null;
		BufferedImage eyelessgirl = null;
		BufferedImage halfbearhalfbear = null;
		BufferedImage mii = null;
		BufferedImage surffer = null;
		BufferedImage revolution = null;
		BufferedImage moon = null;
		BufferedImage heureusegateau = null;
		BufferedImage doratheexplorer = null;
		
		try {
			 ghost = ImageIO.read(ImageLibrary.class.getResourceAsStream("/images/1.jpg"));;
			 zero = ImageIO.read(ImageLibrary.class.getResourceAsStream("/images/2.jpg"));;
			 luffy = ImageIO.read(ImageLibrary.class.getResourceAsStream("/images/3.jpg"));;
			 lizardon = ImageIO.read(ImageLibrary.class.getResourceAsStream("/images/4.jpg"));;
			 nanoha = ImageIO.read(ImageLibrary.class.getResourceAsStream("/images/5.jpg"));;
			 cat = ImageIO.read(ImageLibrary.class.getResourceAsStream("/images/6.jpg"));;
			 jojo = ImageIO.read(ImageLibrary.class.getResourceAsStream("/images/7.jpg"));;
			 burger = ImageIO.read(ImageLibrary.class.getResourceAsStream("/images/8.jpg"));;
			 happyface = ImageIO.read(ImageLibrary.class.getResourceAsStream("/images/9.jpg"));;
			 clown = ImageIO.read(ImageLibrary.class.getResourceAsStream("/images/10.jpg"));;
			 elmo = ImageIO.read(ImageLibrary.class.getResourceAsStream("/images/11.jpg"));;
			 cookiemonster = ImageIO.read(ImageLibrary.class.getResourceAsStream("/images/12.jpg"));;
			 abelardo = ImageIO.read(ImageLibrary.class.getResourceAsStream("/images/13.jpg"));;
			 xd = ImageIO.read(ImageLibrary.class.getResourceAsStream("/images/14.jpg"));;
			 clavin = ImageIO.read(ImageLibrary.class.getResourceAsStream("/images/15.jpg"));;
			 sun = ImageIO.read(ImageLibrary.class.getResourceAsStream("/images/16.jpg"));;
			 mohammed = ImageIO.read(ImageLibrary.class.getResourceAsStream("/images/17.jpg"));;
			 hp = ImageIO.read(ImageLibrary.class.getResourceAsStream("/images/18.jpg"));;
			 thething = ImageIO.read(ImageLibrary.class.getResourceAsStream("/images/19.jpg"));;
			 kids = ImageIO.read(ImageLibrary.class.getResourceAsStream("/images/20.jpg"));;
			 swim = ImageIO.read(ImageLibrary.class.getResourceAsStream("/images/21.jpg"));;
			 blackkentuckychickenguy = ImageIO.read(ImageLibrary.class.getResourceAsStream("/images/22.jpg"));;
			 blondgirl = ImageIO.read(ImageLibrary.class.getResourceAsStream("/images/23.jpg"));;
			 interracial = ImageIO.read(ImageLibrary.class.getResourceAsStream("/images/24.jpg"));;
			 gyaradous = ImageIO.read(ImageLibrary.class.getResourceAsStream("/images/25.jpg"));;
			 masterchief = ImageIO.read(ImageLibrary.class.getResourceAsStream("/images/26.jpg"));;
			 happyfire = ImageIO.read(ImageLibrary.class.getResourceAsStream("/images/27.jpg"));;
			 littleblondgirl = ImageIO.read(ImageLibrary.class.getResourceAsStream("/images/28.jpg"));;
			 togepi = ImageIO.read(ImageLibrary.class.getResourceAsStream("/images/29.jpg"));;
			 moyashimon = ImageIO.read(ImageLibrary.class.getResourceAsStream("/images/30.jpg"));;
			 carlostomate = ImageIO.read(ImageLibrary.class.getResourceAsStream("/images/31.jpg"));;
			 nokidsallowed = ImageIO.read(ImageLibrary.class.getResourceAsStream("/images/32.jpg"));;
			 dragon = ImageIO.read(ImageLibrary.class.getResourceAsStream("/images/33.jpg"));;
			 eyelessgirl = ImageIO.read(ImageLibrary.class.getResourceAsStream("/images/34.jpg"));;
			 halfbearhalfbear = ImageIO.read(ImageLibrary.class.getResourceAsStream("/images/35.jpg"));;
			 mii = ImageIO.read(ImageLibrary.class.getResourceAsStream("/images/36.jpg"));;
			 surffer = ImageIO.read(ImageLibrary.class.getResourceAsStream("/images/37.jpg"));;
			 revolution = ImageIO.read(ImageLibrary.class.getResourceAsStream("/images/38.jpg"));;
			 moon = ImageIO.read(ImageLibrary.class.getResourceAsStream("/images/39.jpg"));;
			 heureusegateau = ImageIO.read(ImageLibrary.class.getResourceAsStream("/images/40.jpg"));;
			 doratheexplorer = ImageIO.read(ImageLibrary.class.getResourceAsStream("/images/41.jpg"));;
			
		} catch (IOException w) {	}
		
		imageDictionary.put("fantasma",  ghost );
		imageDictionary.put("enmascarado",  zero );
		imageDictionary.put("cultivador",  luffy );
		imageDictionary.put("lagarto",  lizardon );
		imageDictionary.put("nena1",  nanoha );
		imageDictionary.put("gato",  cat );
		imageDictionary.put("chico1",  jojo );
		imageDictionary.put("hamburguesa",  burger );
		imageDictionary.put("feliz",  happyface );
		imageDictionary.put("payaso",  clown );
		imageDictionary.put("elmo",  elmo );
		imageDictionary.put("monstruogalletas",  cookiemonster );
		imageDictionary.put("abelardo",  abelardo );
		imageDictionary.put("xD",  xd );
		imageDictionary.put("calvin",  clavin );
		imageDictionary.put("sol",  sun );
		imageDictionary.put("ejecutivo",  mohammed );
		imageDictionary.put("hp",  hp );
		imageDictionary.put("monstruo",  thething );
		imageDictionary.put("nenes",  kids );
		imageDictionary.put("nadador",  swim );
		imageDictionary.put("chico2",  blackkentuckychickenguy );
		imageDictionary.put("chica1",  blondgirl );
		imageDictionary.put("ajedrez",  interracial );
		imageDictionary.put("dragonasiatico",  gyaradous );
		imageDictionary.put("halo",  masterchief );
		imageDictionary.put("fueguito",  happyfire );
		imageDictionary.put("nena2",  littleblondgirl );
		imageDictionary.put("huevo",  togepi );
		imageDictionary.put("germen",  moyashimon );
		imageDictionary.put("carlostomate",  carlostomate );
		imageDictionary.put("prohibido",  nokidsallowed );
		imageDictionary.put("dragon",  dragon );
		imageDictionary.put("chica2",  eyelessgirl );
		imageDictionary.put("oso",  halfbearhalfbear );
		imageDictionary.put("mii",  mii );
		imageDictionary.put("surfista",  surffer );
		imageDictionary.put("letrero",  revolution );
		imageDictionary.put("luna",  moon );
		imageDictionary.put("pastelfeliz",  heureusegateau );
		imageDictionary.put("peruana",  doratheexplorer );
		
		ImageButton lghost  = new ImageButton(new ImageIcon(ghost),"fantasma", e);;
		ImageButton lzero  = new ImageButton(new ImageIcon(zero), "enmascarado", e);;
		ImageButton lluffy  = new ImageButton(new ImageIcon(luffy),"cultivador", e);;
		ImageButton llizardon  = new ImageButton(new ImageIcon(lizardon), "lagarto",e);;
		ImageButton lnanoha  = new ImageButton(new ImageIcon(nanoha),"nena1",e);;
		ImageButton lcat  = new ImageButton(new ImageIcon(cat),"gato",e);;
		ImageButton ljojo  = new ImageButton(new ImageIcon(jojo),"chico1",e);;
		ImageButton lburger  = new ImageButton(new ImageIcon(burger),"hamburguesa",e);;
		ImageButton lhappyface  = new ImageButton(new ImageIcon(happyface),"feliz",e);;
		ImageButton lclown  = new ImageButton(new ImageIcon(clown),"payaso",e);;
		ImageButton lelmo  = new ImageButton(new ImageIcon(elmo),"elmo",e);;
		ImageButton lcookiemonster  = new ImageButton(new ImageIcon(cookiemonster),"monstruogalletas",e);;
		ImageButton labelardo  = new ImageButton(new ImageIcon(abelardo),"abelardo",e);;
		ImageButton lxd  = new ImageButton(new ImageIcon(xd),"xD",e);;
		ImageButton lclavin  = new ImageButton(new ImageIcon(clavin),"calvin",e);;
		ImageButton lsun  = new ImageButton(new ImageIcon(sun),"sol",e);;
		ImageButton lmohammed  = new ImageButton(new ImageIcon(mohammed),"ejecutivo",e);;
		ImageButton lhp  = new ImageButton(new ImageIcon(hp),"hp",e);;
		ImageButton lthething  = new ImageButton(new ImageIcon(thething),"monstruo",e);;
		ImageButton lkids  = new ImageButton(new ImageIcon(kids),"nenes",e);;
		ImageButton lswim  = new ImageButton(new ImageIcon(swim),"nadador",e);;
		ImageButton lblackkentuckychickenguy  = new ImageButton(new ImageIcon(blackkentuckychickenguy),"chico2",e);;
		ImageButton lblondgirl  = new ImageButton(new ImageIcon(blondgirl),"chica1",e);;
		ImageButton linterracial  = new ImageButton(new ImageIcon(interracial),"ajedrez",e);;
		ImageButton lgyaradous  = new ImageButton(new ImageIcon(gyaradous),"dragonasiatico",e);;
		ImageButton lmasterchief  = new ImageButton(new ImageIcon(masterchief),"halo",e);;
		ImageButton lhappyfire  = new ImageButton(new ImageIcon(happyfire),"fueguito",e);;
		ImageButton llittleblondgirl  = new ImageButton(new ImageIcon(littleblondgirl),"nena2",e);;
		ImageButton ltogepi  = new ImageButton(new ImageIcon(togepi),"huevo",e);;
		ImageButton lmoyashimon  = new ImageButton(new ImageIcon(moyashimon),"germen",e);;
		ImageButton lcarlostomate  = new ImageButton(new ImageIcon(carlostomate),"carlostomate",e);;
		ImageButton lnokidsallowed  = new ImageButton(new ImageIcon(nokidsallowed),"prohibido",e);;
		ImageButton ldragon  = new ImageButton(new ImageIcon(dragon),"dragon",e);;
		ImageButton leyelessgirl  = new ImageButton(new ImageIcon(eyelessgirl),"chica2",e);;
		ImageButton lhalfbearhalfbear  = new ImageButton(new ImageIcon(halfbearhalfbear),"oso",e);;
		ImageButton lmii  = new ImageButton(new ImageIcon(mii),"mii",e);;
		ImageButton lsurffer  = new ImageButton(new ImageIcon(surffer),"surfista",e);;
		ImageButton lrevolution  = new ImageButton(new ImageIcon(revolution),"letrero",e);;
		ImageButton lmoon  = new ImageButton(new ImageIcon(moon),"luna",e);;
		ImageButton lheureusegateau  = new ImageButton(new ImageIcon(heureusegateau),"pastelfeliz",e);;
		ImageButton ldoratheexplorer  = new ImageButton(new ImageIcon(doratheexplorer),"peruana",e);;	
		
		add( lghost );
		add( lzero );
		add( lluffy );
		add( llizardon );
		add( lnanoha );
		add( lcat );
		add( ljojo );
		add( lburger );
		add( lhappyface );
		add( lclown );
		add( lelmo );
		add( lcookiemonster );
		add( labelardo );
		add( lxd );
		add( lclavin );
		add( lsun );
		add( lmohammed );
		add( lhp );
		add( lthething );
		add( lkids );
		add( lswim );
		add( lblackkentuckychickenguy );
		add( lblondgirl );
		add( linterracial );
		add( lgyaradous );
		add( lmasterchief );
		add( lhappyfire );
		add( llittleblondgirl );
		add( ltogepi );
		add( lmoyashimon );
		add( lcarlostomate );
		add( lnokidsallowed );
		add( ldragon );
		add( leyelessgirl );
		add( lhalfbearhalfbear );
		add( lmii );
		add( lsurffer );
		add( lrevolution );
		add( lmoon );
		add( lheureusegateau );
		add( ldoratheexplorer );
	}
	
}
